#ifndef PUREUNIX_FONT_H
#define PUREUNIX_FONT_H
/* Generated by tools/gen_font.py from '/System/Library/Fonts/Menlo.ttc' @ 13pt. */

#include <pureunix/types.h>

#define FONT_CELL_W 8
#define FONT_CELL_H 17
#define FONT_FIRST_CHAR 0x20
#define FONT_LAST_CHAR 0x7E

/* Returns FONT_CELL_H bytes, one per row, MSB = leftmost pixel. Falls back
 * to the blank glyph for characters outside the printable ASCII range. */
const uint8_t *font_glyph(char c);

#endif
