import struct
import sys

PALETTE = [
    (0x00, 0x00, 0x00),  # 0 black
    (0x00, 0x00, 0xAA),  # 1 blue
    (0x00, 0xAA, 0x00),  # 2 green
    (0x00, 0xAA, 0xAA),  # 3 cyan
    (0xAA, 0x00, 0x00),  # 4 red
    (0xAA, 0x00, 0xAA),  # 5 magenta
    (0xAA, 0x55, 0x00),  # 6 brown
    (0xAA, 0xAA, 0xAA),  # 7 light grey
    (0x55, 0x55, 0x55),  # 8 dark grey
    (0x55, 0x55, 0xFF),  # 9 light blue
    (0x55, 0xFF, 0x55),  # 10 light green
    (0x55, 0xFF, 0xFF),  # 11 light cyan
    (0xFF, 0x55, 0x55),  # 12 light red
    (0xFF, 0x55, 0xFF),  # 13 light magenta
    (0xFF, 0xFF, 0x55),  # 14 light brown / yellow
    (0xFF, 0xFF, 0xFF),  # 15 white
]

# Truecolor channels are quantized to this step to keep the RLE table small;
# 8 (32 levels/channel, 32768 colors) is fine-grained enough that banding
# isn't visible but still merges long runs of near-identical anti-aliased
# pixels.
QUANT_STEP = 8


def nearest_color(r, g, b):
    best_i = 0
    best_d = None
    for i, (pr, pg, pb) in enumerate(PALETTE):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if best_d is None or d < best_d:
            best_d = d
            best_i = i
    return best_i


def read_bmp(path):
    with open(path, "rb") as f:
        data = f.read()
    assert data[0:2] == b"BM"
    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    width = struct.unpack_from("<i", data, 18)[0]
    height = struct.unpack_from("<i", data, 22)[0]
    bpp = struct.unpack_from("<H", data, 28)[0]
    assert bpp == 24, f"expected 24bpp bmp, got {bpp}"
    top_down = height < 0
    height = abs(height)
    row_size = ((width * 3 + 3) // 4) * 4
    pixels = [[None] * width for _ in range(height)]
    for row in range(height):
        file_row = row if top_down else (height - 1 - row)
        offset = pixel_offset + file_row * row_size
        for col in range(width):
            b, g, r = data[offset + col * 3: offset + col * 3 + 3]
            pixels[row][col] = (r, g, b)
    return width, height, pixels


def quantize(v, step):
    return (v // step) * step


def build_rle(pixels, width, height, step):
    """Row-major RLE: each entry packs an 8-bit run length (1-255) in the
    top byte and a 24-bit RGB color in the low bits. Runs never cross a row
    boundary, so the decoder can walk (row, col) purely from run lengths."""
    entries = []
    for row in pixels:
        col = 0
        while col < width:
            r, g, b = row[col]
            r, g, b = quantize(r, step), quantize(g, step), quantize(b, step)
            run = 1
            while col + run < width:
                nr, ng, nb = row[col + run]
                nr, ng, nb = quantize(nr, step), quantize(ng, step), quantize(nb, step)
                if (nr, ng, nb) != (r, g, b) or run == 255:
                    break
                run += 1
            rgb = (r << 16) | (g << 8) | b
            entries.append((run << 24) | rgb)
            col += run
    return entries


def downsample_to_grid(pixels, width, height, cols, rows_x2):
    """Nearest-neighbor downsample to a cols x rows_x2 grid of palette
    indices, used for the VGA text-mode fallback (no linear framebuffer)."""
    grid = [[0] * cols for _ in range(rows_x2)]
    for gy in range(rows_x2):
        sy = min(height - 1, gy * height // rows_x2)
        for gx in range(cols):
            sx = min(width - 1, gx * width // cols)
            grid[gy][gx] = nearest_color(*pixels[sy][sx])
    return grid


def main():
    src = sys.argv[1]
    out = sys.argv[2]
    width, height, pixels = read_bmp(src)

    rle = build_rle(pixels, width, height, QUANT_STEP)

    text_cols = 80
    text_rows = 25
    fg_grid = downsample_to_grid(pixels, width, height, text_cols, text_rows)
    bg_grid = downsample_to_grid(pixels, width, height, text_cols, text_rows)
    # Reuse one downsample pass for both half-block rows (top/bottom) by
    # sampling at double vertical resolution.
    full_grid = downsample_to_grid(pixels, width, height, text_cols, text_rows * 2)
    fg_grid = full_grid[0::2]
    bg_grid = full_grid[1::2]

    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_bootsplash.py from the PureUNIX mascot artwork. */\n")
        f.write('#include <pureunix/bootsplash.h>\n')
        f.write('#include <pureunix/framebuffer.h>\n')
        f.write('#include <pureunix/vga.h>\n')
        f.write('#include <pureunix/io.h>\n\n')

        f.write("#define SPLASH_W %d\n#define SPLASH_H %d\n\n" % (width, height))
        f.write("/* Truecolor mascot artwork, run-length encoded row-major: each entry\n"
                " * packs an 8-bit run length (1-255, never crossing a row) in the top\n"
                " * byte and a 24-bit RGB color (channels quantized to multiples of %d)\n"
                " * in the low 24 bits. Drawn directly to the linear framebuffer, so this\n"
                " * isn't limited to the 16-color EGA palette like the VGA fallback below. */\n"
                % QUANT_STEP)
        f.write("static const uint32_t splash_rle[] = {\n")
        for i in range(0, len(rle), 8):
            chunk = rle[i:i + 8]
            f.write("    " + ",".join("0x%08X" % v for v in chunk) + ",\n")
        f.write("};\n")
        f.write("#define SPLASH_RLE_COUNT (sizeof(splash_rle) / sizeof(splash_rle[0]))\n\n")

        f.write("#define SPLASH_ROWS %d\n#define SPLASH_COLS %d\n\n" % (text_rows, text_cols))
        f.write("static const uint8_t splash_fg[SPLASH_ROWS][SPLASH_COLS] = {\n")
        for line in fg_grid:
            f.write("    {" + ",".join(str(v) for v in line) + "},\n")
        f.write("};\n\n")
        f.write("static const uint8_t splash_bg[SPLASH_ROWS][SPLASH_COLS] = {\n")
        for line in bg_grid:
            f.write("    {" + ",".join(str(v) for v in line) + "},\n")
        f.write("};\n\n")

        f.write("""/* CMOS RTC seconds register (0x00); only 1 Hz resolution, but this runs
 * before the PIT/IDT are set up so it has no dependency on the rest of
 * kernel init. */
static uint8_t cmos_seconds(void)
{
    outb(0x70, 0x0B);
    bool binary = inb(0x71) & 0x04;
    outb(0x70, 0x00);
    uint8_t sec = inb(0x71);
    return binary ? sec : (uint8_t)(((sec >> 4) * 10) + (sec & 0x0F));
}

static void delay_seconds(uint8_t n)
{
    uint8_t last = cmos_seconds();
    uint8_t elapsed = 0;
    while (elapsed < n) {
        uint8_t now = cmos_seconds();
        if (now != last) {
            elapsed++;
            last = now;
        }
    }
}

void bootsplash_show(void)
{
    const fb_info_t *fb = fb_get_info();
    if (fb->present) {
        /* splash_rle holds the mascot artwork at its native SPLASH_W x
         * SPLASH_H resolution in full 24-bit color; scale it up to the
         * largest integer factor that still fits the framebuffer and
         * center it, decoding runs straight into fb_fill_rect calls. */
        uint32_t scale_x = fb->width / SPLASH_W;
        uint32_t scale_y = fb->height / SPLASH_H;
        uint32_t scale = scale_x < scale_y ? scale_x : scale_y;
        if (scale == 0) {
            scale = 1;
        }
        uint32_t img_w = SPLASH_W * scale;
        uint32_t img_h = SPLASH_H * scale;
        uint32_t ox = fb->width > img_w ? (fb->width - img_w) / 2 : 0;
        uint32_t oy = fb->height > img_h ? (fb->height - img_h) / 2 : 0;

        uint32_t col = 0, row = 0;
        for (size_t i = 0; i < SPLASH_RLE_COUNT; ++i) {
            uint32_t entry = splash_rle[i];
            uint32_t count = entry >> 24;
            uint32_t rgb = entry & 0x00FFFFFFu;
            fb_fill_rect(ox + col * scale, oy + row * scale, count * scale, scale, rgb);
            col += count;
            if (col >= SPLASH_W) {
                col = 0;
                row++;
            }
        }
    } else {
        volatile uint16_t *vga = (volatile uint16_t *)0xB8000;
        for (size_t row = 0; row < SPLASH_ROWS; ++row) {
            for (size_t col = 0; col < SPLASH_COLS; ++col) {
                uint8_t color = splash_fg[row][col] | (uint8_t)(splash_bg[row][col] << 4);
                vga[row * SPLASH_COLS + col] = (uint16_t)0xDF | ((uint16_t)color << 8);
            }
        }
    }
    delay_seconds(5);
    if (fb->present) {
        /* vga_clear() below only repaints the centered 80x25 text-mode
         * grid, which is smaller than the granted framebuffer whenever the
         * bootloader hands back a mode larger than our 640x425 request (e.g.
         * QEMU's std VGA rounding up to a stock VESA mode). Without this,
         * whatever part of the splash falls outside that centered grid -
         * scaled up along with everything else - is left on screen forever. */
        fb_fill_rect(0, 0, fb->width, fb->height, 0x000000);
    }
    vga_clear();
}
""")


if __name__ == "__main__":
    main()
