import struct
import sys

PALETTE = [
    (0x00, 0x00, 0x00),  # 0 black
    (0x00, 0x00, 0xAA),  # 1 blue
    (0x00, 0xAA, 0x00),  # 2 green
    (0x00, 0xAA, 0xAA),  # 3 cyan
    (0xAA, 0x00, 0x00),  # 4 red
    (0xAA, 0x00, 0xAA),  # 5 magenta
    (0xAA, 0x55, 0x00),  # 6 brown
    (0xAA, 0xAA, 0xAA),  # 7 light grey
    (0x55, 0x55, 0x55),  # 8 dark grey
    (0x55, 0x55, 0xFF),  # 9 light blue
    (0x55, 0xFF, 0x55),  # 10 light green
    (0x55, 0xFF, 0xFF),  # 11 light cyan
    (0xFF, 0x55, 0x55),  # 12 light red
    (0xFF, 0x55, 0xFF),  # 13 light magenta
    (0xFF, 0xFF, 0x55),  # 14 light brown / yellow
    (0xFF, 0xFF, 0xFF),  # 15 white
]


def nearest_color(r, g, b):
    best_i = 0
    best_d = None
    for i, (pr, pg, pb) in enumerate(PALETTE):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if best_d is None or d < best_d:
            best_d = d
            best_i = i
    return best_i


def read_bmp(path):
    with open(path, "rb") as f:
        data = f.read()
    assert data[0:2] == b"BM"
    pixel_offset = struct.unpack_from("<I", data, 10)[0]
    header_size = struct.unpack_from("<I", data, 14)[0]
    width = struct.unpack_from("<i", data, 18)[0]
    height = struct.unpack_from("<i", data, 22)[0]
    bpp = struct.unpack_from("<H", data, 28)[0]
    assert bpp == 24, f"expected 24bpp bmp, got {bpp}"
    top_down = height < 0
    height = abs(height)
    row_size = ((width * 3 + 3) // 4) * 4
    pixels = [[None] * width for _ in range(height)]
    for row in range(height):
        file_row = row if top_down else (height - 1 - row)
        offset = pixel_offset + file_row * row_size
        for col in range(width):
            b, g, r = data[offset + col * 3: offset + col * 3 + 3]
            pixels[row][col] = (r, g, b)
    return width, height, pixels


def main():
    src = sys.argv[1]
    out = sys.argv[2]
    width, height, pixels = read_bmp(src)
    assert width == 50 and height == 50, (width, height)

    cols = 80
    rows = 25
    pad = (cols - width) // 2

    fg_rows = []
    bg_rows = []
    for row in range(rows):
        fg_line = []
        bg_line = []
        for col in range(cols):
            src_col = col - pad
            if 0 <= src_col < width:
                top = nearest_color(*pixels[row * 2][src_col])
                bottom = nearest_color(*pixels[row * 2 + 1][src_col])
            else:
                top = 0
                bottom = 0
            fg_line.append(top)
            bg_line.append(bottom)
        fg_rows.append(fg_line)
        bg_rows.append(bg_line)

    with open(out, "w") as f:
        f.write("/* Generated by tools/gen_bootsplash.py from the PureUNIX mascot artwork. */\n")
        f.write('#include <pureunix/bootsplash.h>\n')
        f.write('#include <pureunix/framebuffer.h>\n')
        f.write('#include <pureunix/vga.h>\n')
        f.write('#include <pureunix/io.h>\n\n')
        f.write("#define SPLASH_ROWS %d\n#define SPLASH_COLS %d\n\n" % (rows, cols))
        f.write("static const uint8_t splash_fg[SPLASH_ROWS][SPLASH_COLS] = {\n")
        for line in fg_rows:
            f.write("    {" + ",".join(str(v) for v in line) + "},\n")
        f.write("};\n\n")
        f.write("static const uint8_t splash_bg[SPLASH_ROWS][SPLASH_COLS] = {\n")
        for line in bg_rows:
            f.write("    {" + ",".join(str(v) for v in line) + "},\n")
        f.write("};\n\n")
        f.write("""/* CMOS RTC seconds register (0x00); only 1 Hz resolution, but this runs
 * before the PIT/IDT are set up so it has no dependency on the rest of
 * kernel init. */
static uint8_t cmos_seconds(void)
{
    outb(0x70, 0x0B);
    bool binary = inb(0x71) & 0x04;
    outb(0x70, 0x00);
    uint8_t sec = inb(0x71);
    return binary ? sec : (uint8_t)(((sec >> 4) * 10) + (sec & 0x0F));
}

static void delay_seconds(uint8_t n)
{
    uint8_t last = cmos_seconds();
    uint8_t elapsed = 0;
    while (elapsed < n) {
        uint8_t now = cmos_seconds();
        if (now != last) {
            elapsed++;
            last = now;
        }
    }
}

/* Same 16-color EGA/VGA palette used above and by the framebuffer console,
 * so the splash and later text share exact colors. */
static const uint32_t splash_palette[16] = {
    0x000000, 0x0000AA, 0x00AA00, 0x00AAAA, 0xAA0000, 0xAA00AA, 0xAA5500, 0xAAAAAA,
    0x555555, 0x5555FF, 0x55FF55, 0x55FFFF, 0xFF5555, 0xFF55FF, 0xFFFF55, 0xFFFFFF,
};

void bootsplash_show(void)
{
    const fb_info_t *fb = fb_get_info();
    if (fb->present) {
        /* splash_fg/splash_bg encode an 80x50 logical image (2 pixel rows
         * per text row, the old half-block trick); draw it as real pixels,
         * scaled up and centered on the framebuffer. */
        const uint32_t scale = 4;
        uint32_t img_w = SPLASH_COLS * scale;
        uint32_t img_h = SPLASH_ROWS * 2 * scale;
        uint32_t ox = fb->width > img_w ? (fb->width - img_w) / 2 : 0;
        uint32_t oy = fb->height > img_h ? (fb->height - img_h) / 2 : 0;
        for (size_t row = 0; row < SPLASH_ROWS; ++row) {
            for (size_t col = 0; col < SPLASH_COLS; ++col) {
                uint32_t px = ox + (uint32_t)col * scale;
                uint32_t py_top = oy + (uint32_t)row * 2 * scale;
                fb_fill_rect(px, py_top, scale, scale, splash_palette[splash_fg[row][col]]);
                fb_fill_rect(px, py_top + scale, scale, scale, splash_palette[splash_bg[row][col]]);
            }
        }
    } else {
        volatile uint16_t *vga = (volatile uint16_t *)0xB8000;
        for (size_t row = 0; row < SPLASH_ROWS; ++row) {
            for (size_t col = 0; col < SPLASH_COLS; ++col) {
                uint8_t color = splash_fg[row][col] | (uint8_t)(splash_bg[row][col] << 4);
                vga[row * SPLASH_COLS + col] = (uint16_t)0xDF | ((uint16_t)color << 8);
            }
        }
    }
    delay_seconds(5);
    vga_clear();
}
""")


if __name__ == "__main__":
    main()
