#!/usr/bin/env python3
"""Rasterizes ASCII 0x20-0x7E from a monospace system font into a fixed-size
bitmap font for the PureUNIX framebuffer console, and writes drivers/font.c
and include/pureunix/font.h.

Requires Pillow (pip install Pillow) and a monospace TrueType font on the
machine running this script (not needed to build the kernel itself, since
the generated .c/.h are committed like drivers/bootsplash.c).
"""
import sys

from PIL import ImageFont, ImageDraw, Image

FONT_PATH = sys.argv[1] if len(sys.argv) > 1 else "/System/Library/Fonts/Menlo.ttc"
FONT_SIZE = 13
CELL_W = 8
CELL_H = 17
FIRST_CHAR = 0x20
LAST_CHAR = 0x7E


def render_glyph(font, ch):
    img = Image.new("1", (CELL_W, CELL_H), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=1)
    px = img.load()
    rows = []
    for y in range(CELL_H):
        byte = 0
        for x in range(CELL_W):
            if px[x, y]:
                byte |= 0x80 >> x
        rows.append(byte)
    return rows


def main():
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE, index=0)
    widths = {round(font.getlength(chr(cp)), 3) for cp in range(FIRST_CHAR, LAST_CHAR + 1)}
    assert widths == {float(CELL_W)}, f"font is not monospace at this size: {widths}"

    glyphs = [render_glyph(font, chr(cp)) for cp in range(FIRST_CHAR, LAST_CHAR + 1)]

    with open("include/pureunix/font.h", "w") as f:
        f.write(
            f"""#ifndef PUREUNIX_FONT_H
#define PUREUNIX_FONT_H
/* Generated by tools/gen_font.py from {FONT_PATH!r} @ {FONT_SIZE}pt. */

#include <pureunix/types.h>

#define FONT_CELL_W {CELL_W}
#define FONT_CELL_H {CELL_H}
#define FONT_FIRST_CHAR 0x{FIRST_CHAR:02X}
#define FONT_LAST_CHAR 0x{LAST_CHAR:02X}

/* Returns FONT_CELL_H bytes, one per row, MSB = leftmost pixel. Falls back
 * to the blank glyph for characters outside the printable ASCII range. */
const uint8_t *font_glyph(char c);

#endif
"""
        )

    with open("drivers/font.c", "w") as f:
        f.write(
            f"""/* Generated by tools/gen_font.py from {FONT_PATH!r} @ {FONT_SIZE}pt. */
#include <pureunix/font.h>

static const uint8_t glyphs[FONT_LAST_CHAR - FONT_FIRST_CHAR + 1][FONT_CELL_H] = {{
"""
        )
        for ch, rows in zip(range(FIRST_CHAR, LAST_CHAR + 1), glyphs):
            row_str = ", ".join(f"0x{b:02X}" for b in rows)
            f.write(f"    {{{row_str}}}, /* {chr(ch)!r} */\n")
        f.write(
            """};

static const uint8_t blank_glyph[FONT_CELL_H] = {0};

const uint8_t *font_glyph(char c)
{
    uint8_t uc = (uint8_t)c;
    if (uc < FONT_FIRST_CHAR || uc > FONT_LAST_CHAR) {
        return blank_glyph;
    }
    return glyphs[uc - FONT_FIRST_CHAR];
}
"""
        )


if __name__ == "__main__":
    main()
